try {
  throw new Error('Algo salio mal')
} catch (error) {
  console.log('Hubo un error bastante grave...');
  
}